# Tmux Configuration
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB,foot:RGB,*:RGB"
set -as terminal-features ",*:RGB,*:clipboard,*:cstyle"
set -g mouse on
set -s escape-time 0
set -g focus-events on
set -g set-clipboard on
set -g allow-passthrough on
setw -g aggressive-resize on
set -g detach-on-destroy off
set -g history-limit 50000

# Prefix = Ctrl+b
unbind C-Space
unbind C-b
set -g prefix C-b
bind-key C-b send-prefix

# Panes & Navigation
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

bind -n M-z resize-pane -Z
bind -n M-q kill-pane
bind x kill-pane

# Windows
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -n M-t new-window -c "#{pane_current_path}"
bind t new-window -c "#{pane_current_path}"

# Popups
bind -n M-e display-popup -d "#{pane_current_path}" -w 85% -h 85% -E "@nnn@"
bind -n M-b display-popup -E -w 75% -h 65% -T " 󰖯 Tabs & Windows " "@tmuxWindowPicker@"
bind -n M-a display-popup -E -w 75% -h 65% -T " 󰒉 Sessions & Projects " "@tmuxSessionizer@"
bind -n M-g display-popup -d "#{pane_current_path}" -w 90% -h 85% -E "@lazygit@"
bind -n M-m display-popup -w 85% -h 80% -E "@btm@"
bind -n M-Enter display-popup -d "#{pane_current_path}" -w 80% -h 70% -E "@nu@"

# Copy Mode
set-window-option -g mode-keys vi
bind c copy-mode
bind -n M-PageUp copy-mode -u
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "@wlCopy@"

# Base Status Styling
set -g status "on"
set -g status-position bottom
set -g status-bg default
set -g status-justify absolute-centre
set -g status-left-length 50
set -g status-right-length 50
set -g status-left " #S "
set -g status-right "%H:%M "

# Dynamically source Noctalia theme across all known template destinations
source-file -q ~/.config/tmux/themes/noctalia.conf
source-file -q ~/.config/tmux/noctalia/colors.conf
source-file -q ~/.config/tmux/noctalia/theme.conf
source-file -q ~/.config/tmux/noctalia.conf
