[opener]
edit = [
  { run = '@helix@ "$@"', block = true, desc = "Helix" }
]

[open]
rules = [
  { mime = "text/*", use = [ "edit", "reveal" ] },
  { mime = "application/{json,javascript,x-javascript,xml}", use = [ "edit", "reveal" ] },
  { mime = "application/x-{bat,shellscript,python-code}", use = [ "edit", "reveal" ] },
]