
add_newline = false
format = """$directory$character"""
palette = "noctalia"
right_format = """$nix_shell$git_branch$git_status$c$python$rust$zig$nodejs$cmd_duration"""
command_timeout = 1000

[character]
vicmd_symbol = "[N] >>>"
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[directory]
read_only = " 󰌾"
truncation_length = 3
truncation_symbol = "…/"
style = "bold cyan"

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'
'~/Projects' = '󰲋 Projects'

# --- Nix Shell ---
[nix_shell]
symbol = " "
format = 'via [$symbol($name)]($style) '
style = "bold cyan"
impure_msg = ""
pure_msg = ""

# --- Git ---
[git_branch]
symbol = " "
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "bold magenta"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold red"

# --- Languages ---
[c]
symbol = " "
format = '[$symbol($version(-$name))]($style) '
style = "bold blue"

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
style = "bold yellow"

[rust]
symbol = " "
format = '[$symbol($version)]($style) '
style = "bold red"

[zig]
symbol = " "
format = '[$symbol($version)]($style) '
style = "bold yellow"

[nodejs]
symbol = " "
format = '[$symbol($version)]($style) '
style = "bold green"

# --- Duration ---
[cmd_duration]
min_time = 2_000
format = 'took [$duration]($style) '
style = "bold yellow"

[docker_context]
disabled = true

# >>> NOCTALIA STARSHIP PALETTE >>>
[palettes.noctalia]
blue      = "#74c7ec"
red       = "#f38ba8"
green     = "#a6e3a1"
yellow    = "#f9e2af"
cyan      = "#89dceb"
magenta   = "#cba6f7"
white     = "#cdd6f4"
black     = "#1e1e2e"
# <<< NOCTALIA STARSHIP PALETTE <<<
